# Generated by Django 5.0.1 on 2024-05-10 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6),
        ),
    ]
